src/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf.urls.static import static
from blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls')),
    path('', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete
from django.contrib.auth.decorators import login_required


app_name = 'posts'

urlpatterns = [
    path('', BlogHome.as_view(), name='home'),
    path('create/',  login_required(BlogPostCreate.as_view()), name='create'),
    path('edit/<str:slug>/', BlogPostUpdate.as_view(),  name='edit'),
    path('delete/<str:slug>/', BlogPostDelete.as_view(),  name='delete'),
    path('<str:slug>/', BlogPostDetail.as_view(),  name='post'),
]

src/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.urls import reverse

User = get_user_model()

class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name='Titre')
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_update = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name='Publié')
    content = models.TextField(blank=True, verbose_name='Contenu')
    thumbnail = models.ImageField(blank=True, upload_to='blog')

    class Meta:
        ordering = ['-created_on']
        verbose_name = 'Article'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    @property
    def author_or_default(self):
        return self.author.username if self.author else 'unknow author'

    def get_absolute_url(self):
        return reverse('posts:home') #posts correspond a l'espace de nomage app_name, dans url.py

src/posts/views.py
from posts.models import BlogPost
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class BlogHome(ListView):
    model = BlogPost
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset

        return queryset.filter(published=True)


class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = 'posts/blogpost_create.html'
    fields = ['title', 'content',]


class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = 'posts/blogpost_edit.html'
    fields = ['title', 'content', 'published', ]


class BlogPostDetail(DetailView):
    model = BlogPost
    template_name = 'posts/blogpost_list.html'
    context_object_name = 'post'


@method_decorator(login_required, name='dispatch')
class BlogPostDelete(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('posts:home')

src/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block title %}<title>Delete post</title>{% endblock %}


{% block content %}
    <h1>Delete your post</h1>

    <form method="POST">
        {% csrf_token %}
        <p>Are you sure abbout deleting {{ object }} ?</p>
        <input type="submit" value="delete it">
    </form>
{% endblock %}

src/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}<title>Create post</title>{% endblock %}


{% block content %}
    <h1>Create your post</h1>

    <form method="POST">
        {% csrf_token %}
        <div>{{ form }}</div>
        <input type="submit" value="create">
    </form>
{% endblock %}

src/posts/templates/posts/blogpost_edit.html
{% extends 'base.html' %}

{% block title %}<title>Edit post</title>{% endblock %}


{% block content %}
    <h1>Edit this post</h1>

    <form method="POST">
        {% csrf_token %}
        <div id="form_edit">{{ form }}</div>
        <input id="edit_submit" type="submit" value="edit">
    </form>
{% endblock %}

src/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}

{% block title %}<title>Informations</title>{% endblock %}


{% block content %}
    <h1>Our blog</h1>
    <br><br>

    {% if posts %}
        {% for post in posts %}
            <article>
                <h2><a id="title_clickable" href="{% url 'posts:post' slug=post.slug %}">{{ post.title }}</a></h2>
                <br>
                <div id="block-posts">
                    <h5>Published by : <i>{{ post.author_or_default }}, the {{ post.created_on|date:'M d, Y' }}</i></h5>
                    <p class="content">{{ post.content|safe|truncatewords:10 }}</p>
                </div>
            </article>
            
            <br>
        {% endfor %}
        <p><a href="{% url 'posts:create' %}">Create a post</a></p>
    {% else %}
        <article>
            <h2>{{ post.title }}</h2>
            <br>
            <div id="post-headband">
                <h5>Published by : <i>{{ post.author_or_default }}, the {{ post.created_on|date:'M d, Y' }}</i></h5>
                {% if request.user.is_authenticated %}
                    <div><a id="orange" href="{% url 'posts:edit' slug=post.slug %}">Edit post</a>
                        <a id="red" href="{% url 'posts:delete' slug=post.slug %}">Delete post</a></div>
                {% endif %}
            </div>
            <img id="img_post" src="{{ post.thumbnail.url }}">
            <p class="content">{{ post.content|safe }}</p>
        </article>
        <br>
        <p><a href="{% url 'posts:home' %}">Navigate through posts</a></p>
    {% endif %}
{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>Welcome</title>{% endblock %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>

    <nav>
        <a href="{% url 'posts:home' %}">Homepage</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'posts:create' %}">Create a post</a>
        {% endif %}
    </nav>

    <section id="section">
        {% block content %}<p>Welcome in your favorite blog</p>{% endblock %}
    </section>
</body>
</html>